---
version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN 	# Perform various network-related operations.
      - SYS_MODULE	# Load and unload kernel modules.
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London		#Asia/Kolkata
      - SERVERURL=auto  #optional: auto check public ip addr and assign
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
